# Generated by Django 5.1.3 on 2025-02-12 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='position_interest',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='intern',
            name='position_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='intern',
            name='preferred_provinces',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='intern',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='intern',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
